const catalog = [
  {
    id: 1,
    title: "Dune: Part Two",
    overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    release_date: "2024-02-27",
    vote_average: 8.6,
    runtime: 166,
    genre_ids: [878, 12, 18],
    director: "Denis Villeneuve",
    platforms: ["Max", "Apple TV", "Prime Video"],
    age: "PG-13",
    match: 98,
  },
  {
    id: 2,
    title: "Oppenheimer",
    overview: "The story of J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    poster_path: "/ptpr0kGAckfQkJeJIt8st5dglvd.jpg",
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    release_date: "2023-07-19",
    vote_average: 8.1,
    runtime: 181,
    genre_ids: [18, 36],
    director: "Christopher Nolan",
    platforms: ["Peacock", "Prime Video"],
    age: "R",
    match: 95,
  },
  {
    id: 3,
    title: "Spider-Man: Across the Spider-Verse",
    overview: "Miles Morales returns for an adventure across the multiverse.",
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    release_date: "2023-05-31",
    vote_average: 8.4,
    runtime: 140,
    genre_ids: [16, 28, 12],
    director: "Joaquim Dos Santos",
    platforms: ["Netflix", "Prime Video"],
    age: "PG",
    match: 94,
  },
  {
    id: 4,
    title: "Barbie",
    overview: "Barbie and Ken leave their familiar world for a journey of self-discovery.",
    poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    release_date: "2023-07-19",
    vote_average: 7.0,
    runtime: 114,
    genre_ids: [35, 12],
    director: "Greta Gerwig",
    platforms: ["Max", "Prime Video"],
    age: "PG-13",
    match: 90,
  },
  {
    id: 5,
    title: "Interstellar",
    overview: "A team of explorers travels beyond this galaxy to discover whether mankind has a future among the stars.",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    release_date: "2014-11-05",
    vote_average: 8.5,
    runtime: 169,
    genre_ids: [12, 878, 18],
    director: "Christopher Nolan",
    platforms: ["Paramount+", "Prime Video"],
    age: "PG-13",
    match: 97,
  },
  {
    id: 6,
    title: "The Batman",
    overview: "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    release_date: "2022-03-01",
    vote_average: 7.7,
    runtime: 176,
    genre_ids: [80, 9648, 18],
    director: "Matt Reeves",
    platforms: ["Max"],
    age: "PG-13",
    match: 92,
  },
  {
    id: 7,
    title: "Parasite",
    overview: "Greed and class discrimination threaten the newly formed relationship between a wealthy family and a poor one.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    vote_average: 8.5,
    runtime: 132,
    genre_ids: [35, 53, 18],
    director: "Bong Joon-ho",
    platforms: ["Hulu", "Prime Video"],
    age: "R",
    match: 96,
  },
  {
    id: 8,
    title: "Inception",
    overview: "A skilled thief is offered a chance to have his criminal record erased if he can plant an idea in a target's mind.",
    poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    release_date: "2010-07-15",
    vote_average: 8.4,
    runtime: 148,
    genre_ids: [28, 878, 12],
    director: "Christopher Nolan",
    platforms: ["Max", "Prime Video"],
    age: "PG-13",
    match: 95,
  },
  {
    id: 9,
    title: "Everything Everywhere All at Once",
    overview: "An exhausted laundromat owner is swept into an adventure across the multiverse.",
    poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    release_date: "2022-03-24",
    vote_average: 7.8,
    runtime: 140,
    genre_ids: [28, 878, 35],
    director: "Daniel Kwan and Daniel Scheinert",
    platforms: ["Max", "Prime Video"],
    age: "R",
    match: 91,
  },
  {
    id: 10,
    title: "The Grand Budapest Hotel",
    overview: "A legendary concierge and his young protégé become caught up in a battle over a priceless painting.",
    poster_path: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    release_date: "2014-02-26",
    vote_average: 8.0,
    runtime: 100,
    genre_ids: [35, 18],
    director: "Wes Anderson",
    platforms: ["Disney+", "Prime Video"],
    age: "R",
    match: 88,
  },
  {
    id: 11,
    title: "Free Guy",
    overview: "A bank teller discovers he is actually a background character in an open-world video game.",
    poster_path: "/yc2IfL701hGkNHRgzmF4C6VKO14.jpg",
    release_date: "2021-08-11",
    vote_average: 7.5,
    runtime: 115,
    genre_ids: [35, 28, 12],
    director: "Shawn Levy",
    platforms: ["Disney+", "Prime Video"],
    age: "PG-13",
    match: 85,
  },
  {
    id: 12,
    title: "The Matrix",
    overview: "A computer hacker learns the truth about his reality and his role in the war against its controllers.",
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    release_date: "1999-03-30",
    vote_average: 8.2,
    runtime: 136,
    genre_ids: [28, 878],
    director: "Lana and Lilly Wachowski",
    platforms: ["Max", "Prime Video"],
    age: "R",
    match: 90,
  },
  {
    id: 13,
    title: "Avengers: Endgame",
    overview: "The remaining heroes assemble for one final stand against Thanos.",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    release_date: "2019-04-24",
    vote_average: 8.3,
    runtime: 181,
    genre_ids: [28, 12, 878],
    director: "Anthony and Joe Russo",
    platforms: ["Disney+", "Prime Video"],
    age: "PG-13",
    match: 89,
  },
  {
    id: 14,
    title: "Whiplash",
    overview: "A driven drummer enters a music conservatory led by a ruthless instructor.",
    poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    release_date: "2014-10-10",
    vote_average: 8.5,
    runtime: 107,
    genre_ids: [18, 10402],
    director: "Damien Chazelle",
    platforms: ["Netflix", "Prime Video"],
    age: "R",
    match: 87,
  },
  {
    id: 15,
    title: "Blade Runner 2049",
    overview: "A new blade runner uncovers a secret that could destabilize what remains of society.",
    poster_path: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    release_date: "2017-10-04",
    vote_average: 8.0,
    runtime: 164,
    genre_ids: [878, 9648, 18],
    director: "Denis Villeneuve",
    platforms: ["Prime Video"],
    age: "R",
    match: 93,
  },
  {
    id: 16,
    title: "Spirited Away",
    overview: "A young girl enters a world of spirits and must find a way to rescue her parents.",
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    vote_average: 8.6,
    runtime: 125,
    genre_ids: [16, 14],
    director: "Hayao Miyazaki",
    platforms: ["Max", "Netflix"],
    age: "PG",
    match: 84,
  },
  {
    id: 17,
    title: "Arrival",
    overview: "A linguist is recruited to communicate with visitors whose language reshapes time.",
    poster_path: "/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    release_date: "2016-11-11",
    vote_average: 7.9,
    runtime: 116,
    genre_ids: [878, 18, 9648],
    director: "Denis Villeneuve",
    platforms: ["Max", "Paramount+"],
    age: "PG-13",
    match: 94,
  },
]

export const MOVIE_CATALOG = catalog.map((movie) => ({
  ...movie,
  year: Number(movie.release_date.slice(0, 4)),
  rating: movie.vote_average,
  format: "movie",
  genres: movie.genre_ids.map((id) => ({
    12: "Adventure",
    14: "Fantasy",
    16: "Animation",
    18: "Drama",
    28: "Action",
    35: "Comedy",
    36: "History",
    53: "Thriller",
    80: "Crime",
    878: "Sci-Fi",
    9648: "Mystery",
    10402: "Music",
  })[id]).filter(Boolean),
}))

export const INITIAL_WISHLIST_IDS = [1, 5, 7, 14, 15, 16]

export const HOME_MOVIE_SECTIONS = {
  trending: [9, 6, 2, 17, 13],
  comedy: [4, 10, 11, 7],
  topRated: [5, 7, 14, 16, 8],
  hollywood: [12, 13, 8, 3, 2],
}

export const FEATURED_MOVIE = MOVIE_CATALOG[0]

export const getMovieById = (id) => MOVIE_CATALOG.find((movie) => String(movie.id) === String(id))
